#!/bin/bash

repo_checkout_svn(){
	echo -en "$c_l"
	fc1="$(mktemp)"
	clear
	ologo
	i=0
	COUNT=0

	validate_command "Checking repository URL" check_url "$URL_OSCAM_REPO"

	if [ -d "${repodir}" ]
	then
		rm -rf "${repodir}"
		printf "$p_l\n  $txt_delete oscam-${REPO} $re_\n"
	else
		printf "$p_l\n  $txt_no oscam-${REPO} $txt_found\n$re_"
	fi

	printf "$w_l  ${REPO^^} Repository: $g_l$URL_OSCAM_REPO$re_"
	[ ! -z "$1" ] && [ $(($1)) -gt 6999 ] && opt_="-r$1" && mac_="($txt_selected)" || opt_=''

	printf "\n$w_l  ${REPO^^} FileCount : "
	svn info -R "$URL_OSCAM_REPO" |grep '^URL' |uniq |wc -l >"$fc1"
	n=$(cat "$fc1")
	printf "$g_l""$txt_found $n"
	printf "\n$w_l  ${REPO^^} checkout  : "

	while read line filename
	do
		counter=$(( 100*(++i)/n))
		tput cup 10 18
		[ "$counter" -lt "100" ] && echo -en "$g_l""$counter%$re_" || echo -e "$g_l""100%$re_"
	done < <( svn co "$URL_OSCAM_REPO" $opt_ "${repodir}" |sed "s|${repodir}/||g")

	tput cup 10 18;
	echo -e "$g_l""100%$re_"

	if [ -f "${repodir}/config.sh" ]
	then
		tput cup 11 0;
		printf "$w_l  ${REPO^^} Revision  :$y_l $(REVISION) @ $(BRANCH) $b_l$mac_$re_\n$w_l  ${REPO^^} UserPath  :$y_l ${repodir}"
	fi

	[ -f "${repodir}/config.h" ]&& reset_="$("${repodir}/config.sh" -R)"
	rm -rf "$fc1"
	_nl
	[ -f "$ispatched" ] && rm -f "$ispatched"
	tar_repo
}

repo_update_svn(){
	printf "$c_l"
	clear
	ologo
	i=1

	validate_command "Checking repository URL" check_url "$URL_OSCAM_REPO"

	if [ -d "${repodir}" ]
	then
		printf "$p_l\n  $txt_update oscam-${REPO} $re_\n"
	else
		checkout
		return
	fi

	printf "\n$w_l  ${REPO^^} TrunkURL  : $g_l""$URL_OSCAM_REPO""$re_"
	svn co "$URL_OSCAM_REPO" "${repodir}" -q

	if [ -f "${repodir}/config.sh" ]
	then
		tput cup 10 2
		printf "\n$w_l  ${REPO^^} Revision  : ""$y_l$(REVISION) @ $(BRANCH) $b_l$mac_$re_\n$w_l  ${REPO^^} UserPath  : $y_l""${repodir}\n$re_"
	fi

	if [ -f "${repodir}/config.h" ]
	then
		reset_="$("${repodir}/config.sh" -R)"
	fi
}

# Function to log progress (replace direct command output piping)
log_svn_progress() {
	while read line filename; do
		((++i)); PCT=$((100 * i / (nnn + 1)))
		if [ "$PCT" -gt 0 ]; then
			echo "$PCT"  # This will be piped to ui_show_progressbox
		fi
	done
}

_dialog_checkout1_svn(){
	rm -rf "${repodir}" 2>/dev/null
	COUNT=0
	[ -z "$1" ] && rn=0 || rn="$1"
	if [ "$rn" -ge "7000" ]
	then
		_rev="-r $rn"
		sc_text="Revision: $rn"
	else
		_rev=''
		sc_text="$txt_latest"
	fi

	# Get total file count for progress calculation
	nnn="$(svn info -R "$URL_OSCAM_REPO" |grep "^URL: " |uniq |wc -l)"
	i=0  # Initialize counter here

	# Use ui_show_progressbox instead of direct gui call
	{
		svn co "$URL_OSCAM_REPO" "${repodir}" $_rev | sed "s@${repodir}@@g" | awk '{print $2}' | log_svn_progress
	} | ui_show_progressbox " -[ ${REPO^^} Checkout $sc_text ]- " "Please wait while ${REPO^^} is checked out..."

	# Post-checkout cleanup and config setup
	cd "${repodir}"
	if [ -f "${repodir}/config.sh" ]
	then
		reset_="$("${repodir}/config.sh" -R)"
		printf "Revision: $(REVISION) done..."
		[ -f "$ispatched" ] && rm -f "$ispatched"
		_get_config_menu
	fi
}

svnurl(){
	svn info | sed -ne 's/^URL: //p'
}
